version: "3.6"

services:
  db:
    ports:
      - "5438:5432"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dge_app
      POSTGRES_PASSWORD: password

    volumes:
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
